services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu.gpl
    environment:
      ACCELERATION_BACKEND: "cuda"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
